commands:

  test:
    help: test
    description: execute ruby tests
    command: rake test

  phpunit:
    help: phpunit
    description: execute php tests
    command: ./bin/vendor/phpunit --configuration=tests/phpunit.xml

  ls:
    help: ls
    description: lists /tmp folder
    command: ls /tmp

  ls_with_error:
    description: list folder that does not exist
    command: ls /tmp/file_that_does_not_exist

# to be implemented
groups:
  qa:
    - test
    - phpunit
