commands:

  test:
    help: test
    description: execute ruby tests
    command: rake test

  phpunit:
    help: phpunit
    description: execute php tests
    command: ./bin/vendor/phpunit --configuration=tests/phpunit.xml

  ls:
    description: List /tmp folder
    command: ls /tmp | head

  ls_current:
    description: List current dir
    command: ls .

  ls_with_error:
    description: list folder that does not exist
    command: ls /tmp/file_that_does_not_exist

groups:
  list_all:
    description: list directories
    break_on_failure: true
    commands:
      - ls
      - ls_current

  list_some:
    description: list directories
    break_on_failure: false
    commands:
      - ls
      - ls_current
